### ISSUE TITLE
Swap cursor highlight and selection colors

### ISSUE THREAD

**Issue by valtism** [Vincent-P/gruvbox-intellij-theme#20]
Not sure if this is within the scope of this plugin or I'd have to bring it up with morhetz.

The issue I see is that currently when resting the cursor on a symbol, it highlights it in blue or blue-green, depending on the symbol. Selection of text highlights as a light grey. This seems to be a little backwards as selecting a symbol means that the unselected area is blue while the selected area is grey. 

<img width="193" alt="Screen Shot 2020-04-14 at 11 22 11 am" src="https://user-images.githubusercontent.com/1286001/79175908-480d6480-7e42-11ea-8400-9d2555202ca1.png">

I find this to be confusing as it is the opposite of how selection works visually in browsers and many operating systems. 

Thoughts?

**Comment by Vincent-P** [comment]
After looking at this closely, other builtin color schemes (Intellij Light, Classic Light, Darcula and High Contrast) also have this behavior.
The identifier under the caret has a different background color.
So I guess the issue is that the background color could be changed to something other than blue?
Builtins color schemes use a redish color.

EDIT: I have updated the colors to match the semantics of other Jetbrains themes, green for identifiers and red for writable identifiers.

**Comment by Vincent-P** [comment]
Please reopen if you think that the selection is still confusing.
